/**
 * ============================================================================
 * mockMatches.ts — Datos de ejemplo para desarrollar el frontend SIN backend
 * ============================================================================
 * Se usan automáticamente como fallback en matchService.ts cuando el fetch
 * al backend Java falla (ej. backend aún no levantado en local). Bórralo o
 * desactiva el fallback en matchService.ts cuando el backend esté listo.
 * ============================================================================
 */

import { Match } from "@/types";

export const MOCK_MATCHES: Match[] = [
  {
    id: "1",
    tournament: "Mundial - Partidos",
    homeTeam: { id: "nl", name: "Países Bajos" },
    awayTeam: { id: "ma", name: "Marruecos" },
    startTime: new Date().toISOString(),
    status: "LIVE",
    liveMinute: "98:19",
    homeScore: 1,
    awayScore: 1,
    isBoosted: true,
    boostLabel: "25%",
    mainMarket: {
      id: "m1",
      type: "MATCH_WINNER",
      name: "Resultado del Tiempo Extra",
      odds: [
        { id: "o1", label: "1", value: 4.2, marketType: "MATCH_WINNER" },
        { id: "o2", label: "X", value: 1.7, marketType: "MATCH_WINNER" },
        { id: "o3", label: "2", value: 4.15, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "2",
    tournament: "Mundial",
    homeTeam: { id: "fr", name: "Francia" },
    awayTeam: { id: "se", name: "Suecia" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
    status: "SCHEDULED",
    mainMarket: {
      id: "m2",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o4", label: "1", value: 1.34, marketType: "MATCH_WINNER" },
        { id: "o5", label: "X", value: 5.9, marketType: "MATCH_WINNER" },
        { id: "o6", label: "2", value: 9.5, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
  {
    id: "3",
    tournament: "Mundial",
    homeTeam: { id: "ci", name: "Costa de Marfil" },
    awayTeam: { id: "no", name: "Noruega" },
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
    status: "SCHEDULED",
    isBoosted: true,
    boostLabel: "20%",
    mainMarket: {
      id: "m3",
      type: "MATCH_WINNER",
      name: "Resultado del partido",
      odds: [
        { id: "o7", label: "1", value: 3.6, marketType: "MATCH_WINNER" },
        { id: "o8", label: "X", value: 3.45, marketType: "MATCH_WINNER" },
        { id: "o9", label: "2", value: 2.18, marketType: "MATCH_WINNER" },
      ],
    },
  },
];